### ISSUE TITLE
Change Module Name

### ISSUE THREAD

**Issue by eOnofri04** [eOnofri04/AlphaShape.jl#7]
Penso che potrebbe essere una buona idea cambiare il nome del modulo in qualcosa come:
 - `AlphaStructures.jl` <- Io voto questo
 - `PersistentHomology.jl`
 - `PersistencyEvaluation.jl`
 - `AlphaHomology.jl`
Tu cosa ne pensi @marteresagh

**Comment by marteresagh** [comment]
si hai ragione, AlphaStructures.jl va bene anche a me
